/**
 * This file is part of ncmjb.
 * ncmjb is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ncmjb is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ncmjb.  If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mplayeripc_MPlayerSharedMemory */

#ifndef _Included_mplayeripc_MPlayerSharedMemory
#define _Included_mplayeripc_MPlayerSharedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mplayeripc_MPlayerSharedMemory
 * Method:    init
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_mplayeripc_MPlayerSharedMemory_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     mplayeripc_MPlayerSharedMemory
 * Method:    getNativeByteBuffer
 * Signature: (IJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_mplayeripc_MPlayerSharedMemory_getNativeByteBuffer
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     mplayeripc_MPlayerSharedMemory
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mplayeripc_MPlayerSharedMemory_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mplayeripc_MPlayerSharedMemory
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mplayeripc_MPlayerSharedMemory_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mplayeripc_MPlayerSharedMemory
 * Method:    startShmSettingDeamon
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mplayeripc_MPlayerSharedMemory_startShmSettingDeamon
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
